[package]
name = "rusterizer"
version = "0.1.0"
authors = ["Niklas Wallgren <niklasandersjonsson@gmail.com>"]
edition = "2021"

[dependencies]
minifb = "0.16.0" # Minimal crate for window + frame buffer creation
png = "0.16.2"    # For loading textures


[profile.release]
debug = true
